name: check commit content

on: 
    pull_request: 
      types: 
        - closed

jobs: 
    if_merged:
      runs-on: ubuntu-latest
      steps: 
        - run: 
           - echo "test lock merge"
           - echo "github.event.pull_request"
           - exit 1

